plugins:
  discourse_dictionary_enabled:
    default: true
    client: true
  discourse_dictionary_oxford_app_id:
    default: ""
  discourse_dictionary_oxford_api_key:
    default: ""
  discourse_dictionary_min_trust_level:
    default: 2
    enum: "TrustLevelAndStaffSetting"
